### ISSUE TITLE
Using the action with the Github Workflow

### ISSUE THREAD

**Issue by pipex** [tmigone/balena-versionist-action#4]
Not so much of an issue but more of a question for discussion.

Is there a way to use the action with the pull request/approve (github) workflow?

I tested this by replacing the trigger of the workflow for

```
on:
 pull_request:
    types: [opened, synchronize, closed]
    branches:
      - master
```

The action ran correctly on push to the PR branch, but it immediately created the tag and merged the branch to master even though some of the other jobs failed. I know this is my own fault as the documentation does not say anything about this workflow, but it would be desirable to have this feature to run the action along other jobs that can push draft images to dockerhub, for instance.

**Comment by tmigone** [comment]
@pipex I'm not sure I follow. If you open a PR using

```
on:
  push:
    branches:
      - master
```

it won't run until you merge it (so after PR review, approve, etc). Is that not the behavior you observed?
